package com.nershield.rainfall.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import java.util.List;

/**
 * SHAP (TreeSHAP, exact) attribution for one lead time of a rainfall forecast, proxied from
 * the Python AI service's {@code POST /rainfall/explain[/demo]}.
 *
 * <p>Only available when the AI service has the XGBoost co-forecaster loaded — TreeSHAP is
 * exact for tree ensembles, never for the LSTM (see {@code ml-service/docs/ne_rainfall/SHAP.md}).
 * A request when it isn't loaded gets a {@code 503}, never a fabricated explanation.
 *
 * @param additivityError how exactly the contributions sum to the prediction in the model's
 *     own output space — near-zero, not a confidence figure.
 * @param narrative plain-English summary of the top contributions, generated by the AI service.
 * @param contributions ranked feature contributions — see {@link FeatureContributionResponse}
 *     for why {@code effectMm} figures don't sum to {@code predictionMm}.
 */
public record RainfallExplanationResponse(
        int horizon,
        @JsonAlias("lead_time_min") int leadTimeMin,
        @JsonAlias("prediction_mm") double predictionMm,
        @JsonAlias("base_mm") double baseMm,
        @JsonAlias("additivity_error") double additivityError,
        @JsonAlias("units_note") String unitsNote,
        String narrative,
        List<FeatureContributionResponse> contributions) {}
